import { Router } from "express";
import * as SubscriptionCtlr from "../controllers/subscription.controller";
import { verifyTokenMiddleware } from "../middlewares/verifyToken";
const router = Router();
router.get("/prices", SubscriptionCtlr.getPrices);
router.use(verifyTokenMiddleware);
router.get("/", SubscriptionCtlr.listSubscriptions);
router.post("/create", SubscriptionCtlr.createElementsSubscription);
router.post("/cancel", SubscriptionCtlr.cancelSubscription);
router.post("/update", SubscriptionCtlr.updateSubscription);
export default router;
